name: Test quick setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
    - *.sh

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run setup script
        run: sudo ./installer.sh
